const CLOUDINARY_NAME = "dk824teal";
const CLOUDINARY_API_KEY = "441964684332735";
const CLOUDINARY_API_SECRET = "9jXUTvXqxo668ZBdGAWdavcNTFY";
const LIVELY_PRESET = "suhi4qbk";

module.exports = {
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  LIVELY_PRESET,
};
