name: Deploy to AWS CodeCommit

on:
  push:
    branches: 
      - main

jobs:
  to_codecommit:                                        # <-- different jobs are executed in parallel.
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
            
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url:
              ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/Lively-AWS
            ssh_private_key:
              ${{ secrets.AWS_ACCESS_KEY_ID }}
            ssh_username:                                 # <-- (for codecommit) you need to specify ssh-key-id as ssh username.
              ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
